# Generated by Django 4.2.7 on 2025-09-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('content', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('date_gmt', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('modified_gmt', models.DateTimeField()),
                ('status', models.CharField(default='publish', max_length=50)),
                ('post_type', models.CharField(default='post', max_length=50)),
                ('featured_media_id', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('video_sources', models.JSONField(blank=True, default=list)),
                ('download_links', models.JSONField(blank=True, default=list)),
                ('author_id', models.IntegerField(default=1)),
                ('comment_status', models.CharField(default='open', max_length=20)),
                ('ping_status', models.CharField(default='open', max_length=20)),
                ('is_sticky', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('scraped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='movies.category')),
                ('tags', models.ManyToManyField(blank=True, to='movies.tag')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('season_number', models.PositiveIntegerField(default=1)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.series')),
            ],
            options={
                'ordering': ['season_number', 'episode_number'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['date'], name='movies_movi_date_de22a4_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='movies_movi_slug_5ef9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status'], name='movies_movi_status_ba6bc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('series', 'season_number', 'episode_number')},
        ),
    ]
