# Generated by Django 5.2.4 on 2026-08-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="telegram_post_type",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="movie",
            name="telegram_posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
