# Generated by Django 5.2.4 on 2026-09-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_telegram_post_type_movie_telegram_posted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="canonical_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
