# Generated by Django 5.2.4 on 2026-09-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_canonical_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
